### ISSUE TITLE
Water vapor function

### ISSUE THREAD

**Issue by Gorkowski** [uncscode/parcelona#2]
write a function that interfaces with particula environmental class, to calculate the vapor pressure with respect to water

https://en.wikipedia.org/wiki/Vapour_pressure_of_water

**Comment by ngam** [comment]
Can we use the Buck equation here or is it too simplistic? If so, we can just add it to `particula` at some point.

$$ P = 0.61121 \times \exp{\left(\left(18.678 - \frac{T}{234.5}\right) \left(\frac{T}{257.14+T}\right)\right)} $$ 

We need to add a "dynamic" environment class for the parcel; so that we can either grow it (append a list or array) or replace previous values
